M48
; DRILL file {KiCad 6.0.2+dfsg-1} date Sat 15 Nov 2025 07:04:58 PM CET
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-11-15T19:04:58+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,6.0.2+dfsg-1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X3.7307Y-2.0496
X3.8307Y-2.0496
T2
X3.7835Y-1.7992
T0
M30
